/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesMigrationPreviewRouteImport } from './routes/recipes.migration-preview'
import { Route as IngredientsReviewRouteImport } from './routes/ingredients.review'

const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesMigrationPreviewRoute = RecipesMigrationPreviewRouteImport.update({
  id: '/migration-preview',
  path: '/migration-preview',
  getParentRoute: () => RecipesRoute,
} as any)
const IngredientsReviewRoute = IngredientsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => IngredientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/ingredients': typeof IngredientsRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/ingredients/review': typeof IngredientsReviewRoute
  '/recipes/migration-preview': typeof RecipesMigrationPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/ingredients': typeof IngredientsRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/ingredients/review': typeof IngredientsReviewRoute
  '/recipes/migration-preview': typeof RecipesMigrationPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/ingredients': typeof IngredientsRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/ingredients/review': typeof IngredientsReviewRoute
  '/recipes/migration-preview': typeof RecipesMigrationPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/ingredients'
    | '/invoices'
    | '/login'
    | '/recipes'
    | '/ingredients/review'
    | '/recipes/migration-preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/ingredients'
    | '/invoices'
    | '/login'
    | '/recipes'
    | '/ingredients/review'
    | '/recipes/migration-preview'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/ingredients'
    | '/invoices'
    | '/login'
    | '/recipes'
    | '/ingredients/review'
    | '/recipes/migration-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  IngredientsRoute: typeof IngredientsRouteWithChildren
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  RecipesRoute: typeof RecipesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/migration-preview': {
      id: '/recipes/migration-preview'
      path: '/migration-preview'
      fullPath: '/recipes/migration-preview'
      preLoaderRoute: typeof RecipesMigrationPreviewRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/ingredients/review': {
      id: '/ingredients/review'
      path: '/review'
      fullPath: '/ingredients/review'
      preLoaderRoute: typeof IngredientsReviewRouteImport
      parentRoute: typeof IngredientsRoute
    }
  }
}

interface IngredientsRouteChildren {
  IngredientsReviewRoute: typeof IngredientsReviewRoute
}

const IngredientsRouteChildren: IngredientsRouteChildren = {
  IngredientsReviewRoute: IngredientsReviewRoute,
}

const IngredientsRouteWithChildren = IngredientsRoute._addFileChildren(
  IngredientsRouteChildren,
)

interface RecipesRouteChildren {
  RecipesMigrationPreviewRoute: typeof RecipesMigrationPreviewRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesMigrationPreviewRoute: RecipesMigrationPreviewRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  IngredientsRoute: IngredientsRouteWithChildren,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  RecipesRoute: RecipesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
